name: Java Lint (Windows)

on:
  push:
    branches:
      - src.com.interpreter.yaz.main
  pull_request:
    branches:
      - src.com.interpreter.yaz.main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle.zip https://github.com/checkstyle/checkstyle/releases/latest/download/checkstyle-x.x-all.jar
          mkdir checkstyle
          move checkstyle.zip checkstyle
          cd checkstyle
          unzip checkstyle.zip

      - name: Run Checkstyle
        run: |
          java -jar checkstyle/checkstyle-x.x-all.jar -c /google_checks.xml src/**/*.java
