name: Java Build (Windows)

on:
  push:
    branches:
      - src.com.interpreter.yaz.main
  pull_request:
    branches:
      - src.com.interpreter.yaz.main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Compile Java files
        run: |
          javac -d out src/**/*.java

      - name: Run Java program
        run: |
          java -cp out com.interpreter.yaz.Main # Replace with your main class path
